---
name: CI

on:
  push:
  workflow_call:

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 19, 20, 21]
        semantic-release: [22, 23]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn install --immutable
      - run: yarn add --dev semantic-release@~${{ matrix.semantic-release }}
      - run: yarn compile
      - run: yarn lint
      - run: yarn test
  check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJson(needs) }}
